flaskproject/requests/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, SubmitField, TextAreaField, PasswordField
from wtforms.validators import DataRequired, Email, InputRequired
from flaskproject.requests.utils import MultiCheckboxField

class RequestForm(FlaskForm):
    subject=StringField('Subject', validators=[DataRequired()])
    content=TextAreaField('Content', validators=[DataRequired()])
    teams=MultiCheckboxField('Teams', coerce=int, validators=[InputRequired()])
    submit=SubmitField('Review')

class ReviewRequestForm(FlaskForm):
    subject=StringField('Subject')
    content=TextAreaField('Content')
    teams=TextAreaField('Teams')
    submit=SubmitField('Continue')

class EmailCheckForm(FlaskForm):
    email=StringField('Email', validators=[DataRequired(), Email()])
    password=PasswordField('Password',validators=[DataRequired()])
    recaptcha=RecaptchaField()
    submit=SubmitField('Send Emails')

flaskproject/main/routes.py
from flask import render_template, request, Blueprint

main=Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html', title='Home')

@main.route('/about')
def about():
    return render_template('about.html', title='About')

flaskproject/requests/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, session
from flask.globals import current_app
from flask_login import current_user, login_required
from flaskproject import db, mail
from flaskproject.models import Request, Team, Coach
from flaskproject.requests.forms import RequestForm, EmailCheckForm, ReviewRequestForm
from flask_mail import Message
from flaskproject.requests.utils import default_subject, default_content, send_emails

requests=Blueprint('requests', __name__)

@requests.route("/request/info", methods=['GET', 'POST'])
@login_required
def request_info():
    teamsChoices = [{"id": row.id, "name": row.name, "division": row.division, "conference": row.conference, "state":row.state} for row in Team.query.all()]
    teamsChoices=sorted(teamsChoices, key=lambda i: (i['name']))
    print(teamsChoices)
    divisions=[]
    for team in Team.query.all():
        divisions.append(team.division)
    divisions=list(set(divisions))
    divisions.sort()
    conferences=[]
    for team in Team.query.all():
        conferences.append(team.conference)
    conferences=list(set(conferences))
    conferences.sort()
    states=[]
    for team in Team.query.all():
        states.append(team.state)
    states=list(set(states))
    states.sort()

    #if request.method == 'POST':

    return render_template('request_info.html', title='New Request', teamsChoices=teamsChoices, divisions=divisions, conferences=conferences, states=states, default_subject=default_subject, default_content=default_content)

@requests.route("/submit_request_info", methods=['GET', 'POST'])
@login_required
def submit_request_info():
    session['subject']=request.get_json()['subject']
    session['content']=request.get_json()['content']
    session['teams']=request.get_json()['teams']
    print(session['teams'])
    return redirect(url_for('requests.review_request'))

@requests.route("/request/new", methods=['GET', 'POST'])
@login_required
def new_request():
    form=RequestForm()
    form.teams.choices = [(row.id, f'{row.name} ({row.division}, {row.conference}, {row.state})') for row in Team.query.all()]
    if form.validate_on_submit():
        session['subject']=form.subject.data
        session['content']=form.content.data
        session['teams']=form.teams.data
        return redirect(url_for('requests.review_request'))
    return render_template('create_request.html', title='New Request', form=form, default_subject=default_subject, default_content=default_content)

@requests.route("/request/review", methods=['GET', 'POST'])
@login_required
def review_request():
    if not 'subject' in session or not 'content' in session or not 'teams' in session:
        flash('Session expired! Please fill the form again.', 'danger')
        return redirect(url_for('requests.new_request'))
    form=ReviewRequestForm()
    teams=''
    for team in session['teams']:
        teams = teams + Team.query.filter_by(id=team['id']).first().name + '; '
    subject=session['subject'].replace("[team]", Team.query.filter_by(id=team['id']).first().name).replace("[division]", Team.query.filter_by(id=team['id']).first().division).replace("[conference]", Team.query.filter_by(id=team['id']).first().conference).replace("[state]", Team.query.filter_by(id=team['id']).first().state).replace("[mascot]", Team.query.filter_by(id=team['id']).first().mascot).replace("[coach-first-name]", Coach.query.filter_by(team_id=team['id']).first().first_name).replace("[coach-last-name]", Coach.query.filter_by(team_id=team['id']).first().last_name)
    content=session['content'].replace("[team]", Team.query.filter_by(id=team['id']).first().name).replace("[division]", Team.query.filter_by(id=team['id']).first().division).replace("[conference]", Team.query.filter_by(id=team['id']).first().conference).replace("[state]", Team.query.filter_by(id=team['id']).first().state).replace("[mascot]", Team.query.filter_by(id=team['id']).first().mascot).replace("[coach-first-name]", Coach.query.filter_by(team_id=team['id']).first().first_name).replace("[coach-last-name]", Coach.query.filter_by(team_id=team['id']).first().last_name)
    if form.validate_on_submit():
        return redirect(url_for('requests.check_email'))
    return render_template('review_request.html', title='Review Request', form=form, subject=subject, content=content, teams=teams)
    
@requests.route("/request/check_email", methods=['GET','POST'])
@login_required
def check_email():
    if not 'subject' in session or not 'content' in session or not 'teams' in session:
        flash('Session expired! Please fill the form again.', 'danger')
        return redirect(url_for('requests.new_request'))
    form=EmailCheckForm()
    if form.validate_on_submit():
        current_app.config.update(dict(
            MAIL_USERNAME=form.email.data,
            MAIL_PASSWORD=form.password.data
        ))
        mail.init_app(current_app)
        msg=Message('Test',sender=form.email.data, recipients=['collegeemailsgenerator@gmail.com'])
        try:
            mail.send(msg)
        except:
            flash('Error! The email and password are invalid or the less secure apps on your gmail account is turned off.','danger')
        else:
            emails_request=Request(email=form.email.data, subject=session['subject'], content=session['content'], sender=current_user)
            db.session.add(emails_request)
            for team in session['teams']:
                emails_request.teams.append(Team.query.filter_by(id=team['id']).first())
            db.session.commit()
            send_emails(form.email.data, form.password.data)
            session.pop('subject')
            session.pop('content')
            session.pop('teams')
            flash('Your emails have been sent!', 'success')
            return redirect(url_for('main.home'))
    return render_template('check_email.html', title='New Request', form=form)

@requests.route("/request/<int:request_id>")
def request_details(request_id):
    emails_request=Request.query.get_or_404(request_id)
    if emails_request.sender.email != current_user.email:
        return redirect(url_for('main.home'))
    return render_template('request.html', subject=emails_request.subject, emails_request=emails_request)

flaskproject/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskproject import db, bcrypt
from flaskproject.models import User, Request
from flaskproject.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskproject.users.utils import send_reset_email

users=Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RegistrationForm()
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(email=form.email.data,password=hashed_password)
        db.session.add(user)
        db.session.commit()
        user=User.query.filter_by(email=form.email.data).first()
        login_user(user, remember=form.remember.data)
        flash(f'Welcome {form.email.data}!', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful!', 'danger')
    return render_template('Login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    flash('Logout successful!', 'success')
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form=UpdateAccountForm()
    if form.validate_on_submit():
        current_user.email=form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('main.account'))
    elif request.method=='GET':
        form.email.data=current_user.email
    return render_template('account.html', title='Account', form=form)

@users.route("/userrequests")
@login_required
def user_requests():
    page=request.args.get('page', 1, type=int)
    user=User.query.filter_by(email=current_user.email).first()
    requests=Request.query.filter_by(sender=current_user).order_by(Request.date_submitted.desc()).paginate(page=page, per_page=7)
    return render_template('user_requests.html', requests=requests, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RequestResetForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Instructions to reset your password has been sent to your email!', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user=User.verify_reset_token(token)
    if user is None:
        flash('That is an expired or invalid token', 'warning')
        return redirect(url_for('users.reset_request'))
    form=ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_password
        db.session.commit()
        flash(f'Your password has been updated!', 'success')
        return redirect(url_for('main.home'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskproject/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>about!</h1>
{% endblock content %}

flaskproject/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <div class="media-body">
                <h2 class="account-heading text-center">{{ current_user.email }}</h2>
            </div>
        </div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskproject/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>home!</h1>
{% endblock content %}

flaskproject/templates/layout.html
<!doctype html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="//cdnjs.cloudflare.com/ajax/libs/axios/0.15.3/axios.min.js"></script>

    <script src="https://cdn.ckeditor.com/4.16.2/full/ckeditor.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.js"></script>

    <script src="https://kit.fontawesome.com/3a90cc636e.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css') }}">

    {% if title %}
        <title>College Emails Generator - {{ title }}</title>
    {% else %}
        <title>College Emails Generator</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">College Emails Generator</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('requests.request_info') }}">New Request</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.user_requests') }}">My Requests</a>
                  <!--<a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>-->
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-12">
            {% with messages=get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskproject/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.recaptcha }}
                    {% if form.recaptcha.errors %}
                        <div>
                            <span class="recaptcha-error">Please fill the reCAPTCHA field.</span>
                        </div>
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskproject/templates/request.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_requests') }}">{{ emails_request.email }}</a>
        <small>{{ emails_request.name }}</small>
        <small class="text-muted">{{ emails_request.date_submitted.strftime('%m/%d/%Y') }}</small>
      </div>
      <h2 class="article-title mb-4">{{ emails_request.subject }}</h2>
      <!--<p class="article-content">{{ emails_request.content }}</p>-->
      <div id="content" class="overflow-auto text-wrap" style="word-break: break-word;"></div>
      <p class="text-muted">Teams: {% for team in emails_request.teams %} {{ team.name }}; {% endfor %}</p>
    </div>
    <script type="text/javascript">
      document.getElementById("content").innerHTML= {{emails_request.content | tojson}};
    </script>
  </article>
{% endblock content %}

flaskproject/templates/request_info.html
{% extends "layout.html" %}
{% block content %}
<div id="app" class="content-section">
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">New Request</legend>
        <div class="form-group">
            <label class="form-control-label"><b>Use the following combinations to express the corresponded data (the combinations are case sensative and sensative to white spaces):</b></label>
            <label class="form-control-label">[team] - the college's name (e.g. NJIT)</label><br>
            <label class="form-control-label">[division] - the college's division (e.g. NCAA division I)</label><br>
            <label class="form-control-label">[conference] - the college's conference (e.g. America East)</label><br>
            <label class="form-control-label">[state] - the college's name (e.g. Alabama)</label><br>
            <label class="form-control-label">[mascot] - the college's mascot (e.g. lion)</label><br>
            <label class="form-control-label">[coach-first-name] - the coach's first name (e.g. John)</label><br>
            <label class="form-control-label">[coach-last-name] - the coach's last name (e.g. James)</label>
        </div>
        <div class="form-group">
            <label class="form-control-label">Subject</label>
            <input class="form-control" id="subject" placeholder='{{ default_subject }}' v-model="subject">
            <span class="recaptcha-error" v-if="subjectError">This field is required.</span>
        </div>
        <div class="form-group">
            <label class="form-control-label">Content</label>
            <ckeditor class="form-control" id="content_section" placeholder='{{ default_content }}' v-model="content"></ckeditor>
            <span class="recaptcha-error" v-if="contentError">This field is required.</span>
        </div>
        <div id="app" class="form-group row">      
            <div class="col-lg-5 col-md-5 col-sm-12 align-self-end">
                <label class="form-control-label">Teams</label>
                <select class="form-select col-lg-12 col-md-12 col-sm-12 mb-2" aria-label="Default select example" v-model="divisionSelected" @change="filter">
                    <option value="" selected>Division</option>
                    {% for division in divisions %}
                        <option value='{{division}}'>{{division}}</option>
                    {% endfor %}
                </select>
                <select class="form-select col-lg-12 col-md-12 col-sm-12 mb-2" aria-label="Default select example" v-model="conferenceSelected" @change="filter">
                    <option value="" selected>Conference</option>
                    {% for conference in conferences %}
                        <option value='{{conference}}'>{{conference}}</option>
                    {% endfor %}
                </select>
                <select class="form-select col-lg-12 col-md-12 col-sm-12 mb-3" aria-label="Default select example" v-model="stateSelected" @change="filter">
                    <option value="" selected>State</option>
                    {% for state in states %}
                        <option value='{{state}}'>{{state}}</option>
                    {% endfor %}
                </select>
                <div class="form-control teams-label overflow-auto" style="overflow: auto;">
                    <div class="form-check" v-for="team in nonselectedTeams" :key="team.id" :team="team">
                        <input class="form-check-input" type="checkbox" v-bind:value="team.id" v-bind:id="team.id">
                        <label class="form-check-label" v-bind:for="team.id">[[team.name]]</label>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-12 align-self-center d-flex justify-content-center">
                <div class="btn btn-outline-info" @click="exchange"><i class="fas fa-exchange-alt"></i></div>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-12 align-self-end">
                <label class="form-control-label mb-3">Selected Teams:</label>
                <div class="form-control teams-label overflow-auto" style="overflow: auto;">
                    <div class="form-check" v-for="team in selectedTeams" :key="team.id" :team="team">
                        <input class="form-check-input" type="checkbox" v-bind:value="team.id" v-bind:id='team.id'>
                        <label class="form-check-label" v-bind:for="[[team.id]]">[[team.name]]</label>
                    </div>
                </div>
            </div> 
        </div>
        <span class="recaptcha-error" v-if="teamsError">This field is required.</span>
    </fieldset>
    <div class="btn btn-outline-info mb-3" @click="submit">Review</div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="../static/node_modules/ckeditor4-vue/dist/ckeditor.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script>
        Vue.use( CKEditor );
        new Vue({
            el: '#app',
            delimiters: ['[[', ']]'],
            data:{
                teams: {{teamsChoices|tojson}},
                nonselectedTeams:{{teamsChoices|tojson}},
                selectedTeams:[],
                divisionSelected: '',
                conferenceSelected: '',
                stateSelected: '',
                subjectError: false,
                contentError: false,
                teamsError: false,
                subject:'',
                content:''
            },
            methods:{
                exchange: function(){
                    for(var i=0;i<this.nonselectedTeams.length;i++){
                        if(document.getElementById(this.nonselectedTeams[i].id).checked){
                            document.getElementById(this.nonselectedTeams[i].id).checked=false
                            this.selectedTeams.push(this.nonselectedTeams[i])
                            this.nonselectedTeams.splice(i,1)
                            i--
                        }
                    }
                    for(var i=0;i<this.selectedTeams.length;i++){
                        if(document.getElementById(this.selectedTeams[i].id).checked){
                            document.getElementById(this.selectedTeams[i].id).checked=false
                            this.nonselectedTeams.push(this.selectedTeams[i])
                            this.selectedTeams.splice(i,1)
                            i--
                        }
                    }
                    this.nonselectedTeams.sort(function(a,b) {
                        var textA = a.name.toUpperCase();
                        var textB = b.name.toUpperCase();
                        return (textA < textB) ? -1 : (textA > textB) ? 1 : 0;
                    });
                    this.selectedTeams.sort(function(a,b) {
                        var textA = a.name.toUpperCase();
                        var textB = b.name.toUpperCase();
                        return (textA < textB) ? -1 : (textA > textB) ? 1 : 0;
                    });
                    this.filter()
                },
                filter: function(){
                    this.nonselectedTeams=[...this.teams]
                    for(var i=0;i<this.nonselectedTeams.length;i++){
                        if(this.divisionSelected !== '' && this.divisionSelected !== this.nonselectedTeams[i].division){
                            this.nonselectedTeams.splice(i,1)
                            i--
                            continue
                        }
                        if(this.conferenceSelected !== '' && this.conferenceSelected !== this.nonselectedTeams[i].conference){
                            this.nonselectedTeams.splice(i,1)
                            i--
                            continue
                        }
                        if(this.stateSelected !== '' && this.stateSelected !== this.nonselectedTeams[i].state){
                            this.nonselectedTeams.splice(i,1)
                            i--
                            continue
                        }
                        for(var j=0;j<this.selectedTeams.length;j++){
                            if(this.nonselectedTeams[i].id === this.selectedTeams[j].id){
                                this.nonselectedTeams.splice(i,1)
                                i--
                                break
                            }
                        }
                    }
                },
                submit: function(){
                    this.subjectError = this.subject.trim() === "" ? true : false
                    this.contentError = this.content.trim() === "" ? true : false
                    this.teamsError = this.selectedTeams.length === 0 ? true : false
                    axios.post("{{ url_for('requests.submit_request_info') }}", {
                        subject: this.subject,
                        content: this.content,
                        teams: this.selectedTeams
                    }).then(function(response){
                        window.location.href = "{{ url_for('requests.review_request') }}"
                    })
                }
            }
        });
    </script>
    
</div>
{% endblock content %}

flaskproject/templates/user_requests.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Requests by {{ user.email }} ({{ requests.total }})</h1>
    {% for request in requests.items %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_requests') }}">{{ request.email }}</a>
              <small>{{ request.name }}</small>
              <small class="text-muted">{{ request.date_submitted.strftime('%m/%d/%Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('requests.request_details', request_id=request.id) }}">{{ request.subject }}</a></h2>
            <p class="text-muted">Teams: {% for team in request.teams %} {{ team.name }}; {% endfor %}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in requests.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if requests.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_requests', email=user.email, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_requests', email=user.email, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}